databases:
  - name: movielens-db
    databaseName: movielens

services:
  - type: web
    name: movie-backend
    env: python
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:5000 app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movielens-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: static
    name: movie-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      - key: VITE_TMDB_API_KEY
        value: 259ce8e6ef8a88ab367725c097372b3e
      - key: VITE_API_URL
        fromService:
          type: web
          name: movie-backend
          envVarKey: RENDER_EXTERNAL_URL
